# Generated by Django 4.2 on 2024-12-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="deviceInfoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("throughput", models.IntegerField(default=0)),
                ("verifySpeed", models.IntegerField(default=0)),
                ("avgDelay", models.FloatField(default=0.0)),
                ("verifyMode", models.BooleanField(default=False)),
                ("tableUsage", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="netInfoModel",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("ipAddress", models.CharField(max_length=15)),
                ("mask", models.IntegerField(default=32)),
                ("arriveSpeed", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="portInfoModel",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("ipAddress", models.CharField(max_length=15)),
                ("mask", models.IntegerField(default=32)),
                ("arriveSpeed", models.IntegerField(default=0)),
                ("rx", models.IntegerField(default=0)),
                ("tx", models.IntegerField(default=0)),
            ],
        ),
    ]
