# Generated by Django 4.2 on 2024-12-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("device", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deviceinfomodel",
            name="deviceType",
            field=models.CharField(
                choices=[("router", "路由器"), ("controller", "控制器"), ("terminal", "终端")],
                default="router",
                max_length=20,
            ),
        ),
    ]
