# Generated by Django 4.2 on 2024-12-07 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("device", "0002_deviceinfomodel_devicetype"),
    ]

    operations = [
        migrations.AddField(
            model_name="portinfomodel",
            name="device",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="device.deviceinfomodel",
            ),
        ),
        migrations.AddField(
            model_name="portinfomodel",
            name="portName",
            field=models.CharField(default="default_port", max_length=10),
        ),
    ]
