# Generated by Django 4.2 on 2024-12-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("device", "0004_deviceinfomodel_devicename"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portinfomodel",
            name="device",
        ),
        migrations.AddField(
            model_name="portinfomodel",
            name="deviceName",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
